### ISSUE TITLE
cannot find value `CRED_FLAG_CAPMODE` in crate `bsd_kvm_sys`

### ISSUE THREAD

**Issue by yurivict** [dalance/bsd-kvm#4]
The ```procs``` project fails to build on armv7 with bsd-kvm-0.1.5:

```
error[E0425]: cannot find value `CRED_FLAG_CAPMODE` in crate `bsd_kvm_sys`
   --> src/./columns/state.rs:132:37
    |
132 |         if (cr_flags & bsd_kvm_sys::CRED_FLAG_CAPMODE) != 0 {
    |                                     ^^^^^^^^^^^^^^^^^ not found in `bsd_kvm_sys`
```

[log](https://pkg-status.freebsd.org/ampere2/data/main-armv7-default/pd594ba044905_s6ea1ce222c/logs/procs-0.14.8_2.log)

**Comment by yurivict** [comment]
Duplicate: https://github.com/dalance/bsd-kvm-sys/issues/1
